server:
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    hikari:
      maximum-pool-size: 5
  task:
    scheduling:
      pool:
        size: 10

auth:
  jwt:
    secret-key: eyJhbGciOiJIUzI1NiJ9eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY5ODUxMjMwMSwiaWF0IjoxNjk4NTEyMzAxfQkMdVrwZRf8VyrDh0RH56LUQWZWM7eRKrzWm6MBqzvrk
    expired-second: 604800000
