server:
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    hikari:
      maximum-pool-size: 5
  task:
    scheduling:
      pool:
        size: 10

---

spring:
  profiles:
    active: test
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create

